### PR TITLE
Unit tests and documentation for Util package

### PR DESCRIPTION
**Pull request by danarth**

### CODE REVIEW

**Comment by danarth** [comment]
Added the dont-merge label as I just want to see test coverage updates before merging

**Comment by LoicVerrall** [comment]
Well that was underwhelming 😂

Is that the whole `util` package tested?

**Comment by danarth** [comment]
@msp26ssx @LoicVerrall This PR is now ready for review and merging. If you have any questions @ me 👍

**Review by LoicVerrall — APPROVED** [review]
This looks good. More 'styles' of postcodes will now be accepted!

**Pull request merged**
